# fly.toml app configuration file generated for luxio-web on 2024-02-29T17:51:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'luxio-web'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

